[tool.poetry]
name = "financeapp"
version = "0.1.0"
description = ""
authors = ["Aleksandr Potapkov <potapkov.a.p@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
djangorestframework = "^3.14.0"
djoser = "^2.2.0"
whitenoise = "^6.4.0"
django = "^4.2.1"
gunicorn = "^20.1.0"
drf-yasg = "^1.21.5"
django-cors-headers = "^4.0.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
coverage = "^7.2.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
